import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  pdf,
} from "@react-pdf/renderer";
import type { ReportData } from "../types";

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: "Helvetica" },
  h1: { fontSize: 16, fontWeight: 700, marginBottom: 8 },
  h2: {
    fontSize: 12,
    fontWeight: 700,
    marginTop: 12,
    marginBottom: 4,
    borderBottom: 1,
    paddingBottom: 2,
  },
  meta: { color: "#555", marginBottom: 3, fontSize: 9 },
  section: { marginBottom: 12 },
  controlRow: {
    flexDirection: "row",
    marginBottom: 3,
    paddingBottom: 2,
    borderBottom: "0.5pt solid #ddd",
  },
  controlId: { width: 70, fontWeight: 700, fontSize: 9 },
  controlTitle: { flex: 1, fontSize: 9 },
  controlStatus: { width: 90, fontSize: 9, textAlign: "right" },
  statusOk: { color: "#0a7a3b" },
  statusPartial: { color: "#b27300" },
  statusFail: { color: "#a00" },
  statusNa: { color: "#888" },
});

function statusStyle(s: string) {
  if (s === "implemented") return styles.statusOk;
  if (s === "partial") return styles.statusPartial;
  if (s === "not-implemented") return styles.statusFail;
  return styles.statusNa;
}

function ReportDoc({ data }: { data: ReportData }) {
  const periodLabel = `${data.period.start.toISOString().slice(0, 10)} – ${data.period.end.toISOString().slice(0, 10)}`;
  const byCategory = new Map<string, typeof data.controls>();
  for (const c of data.controls) {
    if (!byCategory.has(c.category)) byCategory.set(c.category, []);
    byCategory.get(c.category)!.push(c);
  }
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.h1}>
          {data.template.id.toUpperCase()} — {data.template.version}
        </Text>
        <Text style={styles.meta}>Organization: {data.org.name}</Text>
        <Text style={styles.meta}>Period: {periodLabel}</Text>
        <Text style={styles.meta}>
          Generated: {data.generatedAt.toISOString()} by {data.generatedBy.name}
        </Text>

        <Text style={styles.h2}>1. Executive Summary</Text>
        <Text style={{ marginBottom: 4 }}>
          Controls: {data.summary.total} total — Implemented:{" "}
          {data.summary.implemented} · Partial: {data.summary.partial} · Not
          implemented: {data.summary.notImplemented} · N/A: {data.summary.na}
        </Text>
        <Text style={{ marginBottom: 4 }}>
          Incidents in period: {data.incidents.length}
        </Text>

        <Text style={styles.h2}>2. Control Matrix</Text>
        {[...byCategory.entries()].map(([cat, controls]) => (
          <View key={cat} wrap={false}>
            <Text
              style={{
                fontSize: 10,
                fontWeight: 700,
                marginTop: 6,
                marginBottom: 2,
              }}
            >
              {cat}
            </Text>
            {controls.map((c) => (
              <View key={c.id} style={styles.controlRow}>
                <Text style={styles.controlId}>{c.id}</Text>
                <Text style={styles.controlTitle}>{c.title}</Text>
                <Text style={[styles.controlStatus, statusStyle(c.status)]}>
                  {c.status}
                </Text>
              </View>
            ))}
          </View>
        ))}

        <Text style={styles.h2}>3. Incidents in Period</Text>
        {data.incidents.length === 0 ? (
          <Text>None.</Text>
        ) : (
          data.incidents.map((i) => (
            <Text key={i.id}>
              {i.openedAt.toISOString().slice(0, 10)} · [{i.severity}] ·{" "}
              {i.status} · {i.title}
            </Text>
          ))
        )}

        <Text style={styles.h2}>4. Audit Highlights</Text>
        {data.auditHighlights.length === 0 ? (
          <Text>None.</Text>
        ) : (
          data.auditHighlights.map((a) => (
            <Text key={a.id}>
              {a.createdAt.toISOString().slice(0, 16)} · {a.action} ·{" "}
              {a.resourceType}
            </Text>
          ))
        )}

        <Text style={styles.h2}>Methodology</Text>
        <Text style={{ fontSize: 8, color: "#666" }}>
          Generated by AIGP-Lite using template {data.template.id} v
          {data.template.version}. Control statuses reflect platform state at
          generation time.
        </Text>
      </Page>
    </Document>
  );
}

export async function renderPdf(data: ReportData): Promise<Buffer> {
  const blob = await pdf(<ReportDoc data={data} />).toBlob();
  return Buffer.from(await blob.arrayBuffer());
}
