import ExcelJS from "exceljs";
import type { ReportData } from "../types";

export async function renderXlsx(data: ReportData): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "AIGP-Lite";
  wb.created = data.generatedAt;

  // Sheet 1: Summary
  const summary = wb.addWorksheet("Summary");
  summary.columns = [
    { header: "Field", key: "k", width: 28 },
    { header: "Value", key: "v", width: 60 },
  ];
  summary.addRows([
    { k: "Template", v: `${data.template.id} (${data.template.version})` },
    { k: "Organization", v: data.org.name },
    {
      k: "Period",
      v: `${data.period.start.toISOString().slice(0, 10)} — ${data.period.end.toISOString().slice(0, 10)}`,
    },
    { k: "Generated at", v: data.generatedAt.toISOString() },
    { k: "Generated by", v: data.generatedBy.name },
    { k: "Total controls", v: data.summary.total },
    { k: "Implemented", v: data.summary.implemented },
    { k: "Partial", v: data.summary.partial },
    { k: "Not implemented", v: data.summary.notImplemented },
    { k: "N/A", v: data.summary.na },
  ]);
  summary.getRow(1).font = { bold: true };

  // Sheet 2: Control Matrix
  const matrix = wb.addWorksheet("Control Matrix");
  matrix.columns = [
    { header: "Category", key: "category", width: 14 },
    { header: "Control ID", key: "id", width: 14 },
    { header: "Title", key: "title", width: 50 },
    { header: "Status", key: "status", width: 16 },
    { header: "Evidence count", key: "evidenceCount", width: 14 },
    { header: "Data source", key: "dataSource", width: 14 },
  ];
  for (const c of data.controls) matrix.addRow(c);
  matrix.getRow(1).font = { bold: true };

  // Sheet 3: Evidence Items
  const evidence = wb.addWorksheet("Evidence Items");
  evidence.columns = [
    { header: "Control ID", key: "cid", width: 14 },
    { header: "Kind", key: "kind", width: 14 },
    { header: "Ref", key: "ref", width: 50 },
    { header: "Captured at", key: "ts", width: 24 },
  ];
  for (const c of data.controls) {
    for (const e of c.evidenceItems) {
      evidence.addRow({
        cid: c.id,
        kind: e.kind,
        ref: e.ref,
        ts: e.capturedAt.toISOString(),
      });
    }
  }
  evidence.getRow(1).font = { bold: true };

  // Sheet 4: Incidents
  const incidents = wb.addWorksheet("Incidents");
  incidents.columns = [
    { header: "Opened", key: "openedAt", width: 22 },
    { header: "Severity", key: "severity", width: 12 },
    { header: "Status", key: "status", width: 14 },
    { header: "Title", key: "title", width: 60 },
  ];
  for (const i of data.incidents) incidents.addRow(i);
  incidents.getRow(1).font = { bold: true };

  // Sheet 5: Audit Trail
  const audit = wb.addWorksheet("Audit Trail");
  audit.columns = [
    { header: "Time", key: "createdAt", width: 22 },
    { header: "Action", key: "action", width: 36 },
    { header: "Resource", key: "resourceType", width: 24 },
    { header: "Actor", key: "actor", width: 24 },
  ];
  for (const a of data.auditHighlights) audit.addRow(a);
  audit.getRow(1).font = { bold: true };

  return Buffer.from((await wb.xlsx.writeBuffer()) as ArrayBuffer);
}
