type OpenApiPathItem = Record<string, unknown>;

type TrpcEndpoint = {
  procedure: string;
  method: "get" | "post" | "patch" | "delete";
  path: string;
  tag: string;
  summary: string;
  requestBody?: boolean;
  parameters?: Array<{
    name: string;
    in: "path" | "query";
    required?: boolean;
    schema?: Record<string, unknown>;
  }>;
};

const jsonBody = {
  required: true,
  content: {
    "application/json": {
      schema: { type: "object", additionalProperties: true },
    },
  },
};

const genericResponse = {
  description: "Successful response",
  content: {
    "application/json": {
      schema: {},
    },
  },
};

const errorResponses = {
  "400": { description: "Bad request" },
  "401": { description: "Unauthorized" },
  "403": { description: "Forbidden" },
  "404": { description: "Not found" },
  "500": { description: "Internal server error" },
};

const idPathParam = (name = "id") => ({
  name,
  in: "path" as const,
  required: true,
  schema: { type: "string" },
});

const limitQueryParam = {
  name: "limit",
  in: "query" as const,
  required: false,
  schema: { type: "integer", minimum: 1, maximum: 200 },
};

const endpoints: TrpcEndpoint[] = [
  {
    procedure: "inventory.list",
    method: "get",
    path: "/trpc/inventory",
    tag: "Inventory",
    summary: "List AI use cases",
  },
  {
    procedure: "inventory.byId",
    method: "get",
    path: "/trpc/inventory/{id}",
    tag: "Inventory",
    summary: "Get an AI use case",
    parameters: [idPathParam()],
  },
  {
    procedure: "inventory.create",
    method: "post",
    path: "/trpc/inventory",
    tag: "Inventory",
    summary: "Create an AI use case",
    requestBody: true,
  },
  {
    procedure: "inventory.update",
    method: "patch",
    path: "/trpc/inventory/{id}",
    tag: "Inventory",
    summary: "Update an AI use case",
    requestBody: true,
    parameters: [idPathParam()],
  },
  {
    procedure: "inventory.remove",
    method: "delete",
    path: "/trpc/inventory/{id}",
    tag: "Inventory",
    summary: "Delete an AI use case",
    parameters: [idPathParam()],
  },
  {
    procedure: "inventory.modelVersionList",
    method: "get",
    path: "/trpc/inventory/{usecaseId}/model-versions",
    tag: "Inventory",
    summary: "List model versions",
    parameters: [idPathParam("usecaseId")],
  },
  {
    procedure: "inventory.modelVersionCreate",
    method: "post",
    path: "/trpc/inventory/{usecaseId}/model-versions",
    tag: "Inventory",
    summary: "Create a model version",
    requestBody: true,
    parameters: [idPathParam("usecaseId")],
  },
  {
    procedure: "inventory.modelVersionUpdate",
    method: "patch",
    path: "/trpc/inventory/model-versions/{id}",
    tag: "Inventory",
    summary: "Update a model version",
    requestBody: true,
    parameters: [idPathParam()],
  },

  {
    procedure: "risk.frameworks",
    method: "get",
    path: "/trpc/risk/frameworks",
    tag: "Risk",
    summary: "List risk frameworks",
  },
  {
    procedure: "risk.controlStatuses",
    method: "get",
    path: "/trpc/risk/usecases/{usecaseId}/controls",
    tag: "Risk",
    summary: "List control statuses",
    parameters: [idPathParam("usecaseId")],
  },
  {
    procedure: "risk.setControlStatus",
    method: "patch",
    path: "/trpc/risk/usecases/{usecaseId}/controls/{controlId}",
    tag: "Risk",
    summary: "Set control status",
    requestBody: true,
    parameters: [idPathParam("usecaseId"), idPathParam("controlId")],
  },
  {
    procedure: "risk.assess",
    method: "post",
    path: "/trpc/risk/usecases/{usecaseId}/assess",
    tag: "Risk",
    summary: "Run use case risk assessment",
    requestBody: true,
    parameters: [idPathParam("usecaseId")],
  },
  {
    procedure: "risk.latestAssessment",
    method: "get",
    path: "/trpc/risk/usecases/{usecaseId}/latest-assessment",
    tag: "Risk",
    summary: "Get latest risk assessment",
    parameters: [idPathParam("usecaseId")],
  },
  {
    procedure: "risk.highRiskCount",
    method: "get",
    path: "/trpc/risk/high-risk-count",
    tag: "Risk",
    summary: "Count high risk use cases",
  },

  {
    procedure: "maturity.questions",
    method: "get",
    path: "/trpc/maturity/questions",
    tag: "Maturity",
    summary: "Get maturity assessment questions",
  },
  {
    procedure: "maturity.latest",
    method: "get",
    path: "/trpc/maturity/latest",
    tag: "Maturity",
    summary: "Get latest maturity scores",
  },
  {
    procedure: "maturity.submit",
    method: "post",
    path: "/trpc/maturity/assessments",
    tag: "Maturity",
    summary: "Submit maturity assessment",
    requestBody: true,
  },
  {
    procedure: "maturity.dashboardSummary",
    method: "get",
    path: "/trpc/maturity/dashboard-summary",
    tag: "Maturity",
    summary: "Get dashboard maturity summary",
  },

  {
    procedure: "policy.list",
    method: "get",
    path: "/trpc/policies",
    tag: "Policy",
    summary: "List policies",
  },
  {
    procedure: "policy.byId",
    method: "get",
    path: "/trpc/policies/{id}",
    tag: "Policy",
    summary: "Get policy",
    parameters: [idPathParam()],
  },
  {
    procedure: "policy.create",
    method: "post",
    path: "/trpc/policies",
    tag: "Policy",
    summary: "Create policy",
    requestBody: true,
  },
  {
    procedure: "policy.update",
    method: "patch",
    path: "/trpc/policies/{id}",
    tag: "Policy",
    summary: "Update policy",
    requestBody: true,
    parameters: [idPathParam()],
  },
  {
    procedure: "policy.remove",
    method: "delete",
    path: "/trpc/policies/{id}",
    tag: "Policy",
    summary: "Delete policy",
    parameters: [idPathParam()],
  },
  {
    procedure: "policy.recentHits",
    method: "get",
    path: "/trpc/policies/recent-hits",
    tag: "Policy",
    summary: "List recent policy hits",
    parameters: [limitQueryParam],
  },
  {
    procedure: "policy.policyHitsThisWeek",
    method: "get",
    path: "/trpc/policies/hits-this-week",
    tag: "Policy",
    summary: "Count policy hits this week",
  },
  {
    procedure: "policy.apiKeys.list",
    method: "get",
    path: "/trpc/policy/api-keys",
    tag: "Policy API Keys",
    summary: "List API keys",
  },
  {
    procedure: "policy.apiKeys.create",
    method: "post",
    path: "/trpc/policy/api-keys",
    tag: "Policy API Keys",
    summary: "Create API key",
    requestBody: true,
  },
  {
    procedure: "policy.apiKeys.revoke",
    method: "delete",
    path: "/trpc/policy/api-keys/{id}",
    tag: "Policy API Keys",
    summary: "Revoke API key",
    parameters: [idPathParam()],
  },

  {
    procedure: "workflow.pendingCount",
    method: "get",
    path: "/trpc/workflows/pending-count",
    tag: "Workflow",
    summary: "Count pending workflows",
  },
  {
    procedure: "workflow.start",
    method: "post",
    path: "/trpc/workflows",
    tag: "Workflow",
    summary: "Start workflow",
    requestBody: true,
  },
  {
    procedure: "workflow.get",
    method: "get",
    path: "/trpc/workflows/{id}",
    tag: "Workflow",
    summary: "Get workflow",
    parameters: [idPathParam()],
  },
  {
    procedure: "workflow.list",
    method: "get",
    path: "/trpc/workflows",
    tag: "Workflow",
    summary: "List workflows",
  },
  {
    procedure: "workflow.decideStep",
    method: "post",
    path: "/trpc/workflows/steps/{stepId}/decision",
    tag: "Workflow",
    summary: "Decide workflow step",
    requestBody: true,
    parameters: [idPathParam("stepId")],
  },

  {
    procedure: "evidence.list",
    method: "get",
    path: "/trpc/evidence",
    tag: "Evidence",
    summary: "List evidence records",
    parameters: [limitQueryParam],
  },
  {
    procedure: "evidence.byId",
    method: "get",
    path: "/trpc/evidence/{id}",
    tag: "Evidence",
    summary: "Get evidence record",
    parameters: [idPathParam()],
  },

  {
    procedure: "audit.list",
    method: "get",
    path: "/trpc/audit",
    tag: "Audit",
    summary: "List audit log entries",
    parameters: [limitQueryParam],
  },

  {
    procedure: "dataLineage.list",
    method: "get",
    path: "/trpc/data-sources",
    tag: "Data Lineage",
    summary: "List data sources",
  },
  {
    procedure: "dataLineage.byId",
    method: "get",
    path: "/trpc/data-sources/{id}",
    tag: "Data Lineage",
    summary: "Get data source",
    parameters: [idPathParam()],
  },
  {
    procedure: "dataLineage.create",
    method: "post",
    path: "/trpc/data-sources",
    tag: "Data Lineage",
    summary: "Create data source",
    requestBody: true,
  },
  {
    procedure: "dataLineage.update",
    method: "patch",
    path: "/trpc/data-sources/{id}",
    tag: "Data Lineage",
    summary: "Update data source",
    requestBody: true,
    parameters: [idPathParam()],
  },
  {
    procedure: "dataLineage.delete",
    method: "delete",
    path: "/trpc/data-sources/{id}",
    tag: "Data Lineage",
    summary: "Delete data source",
    parameters: [idPathParam()],
  },
  {
    procedure: "dataLineage.linkUsecase",
    method: "post",
    path: "/trpc/data-sources/{dataSourceId}/usecases",
    tag: "Data Lineage",
    summary: "Link use case to data source",
    requestBody: true,
    parameters: [idPathParam("dataSourceId")],
  },
  {
    procedure: "dataLineage.unlinkUsecase",
    method: "delete",
    path: "/trpc/data-sources/{dataSourceId}/usecases/{usecaseId}",
    tag: "Data Lineage",
    summary: "Unlink use case from data source",
    requestBody: true,
    parameters: [idPathParam("dataSourceId"), idPathParam("usecaseId")],
  },
  {
    procedure: "dataLineage.byUsecase",
    method: "get",
    path: "/trpc/usecases/{usecaseId}/data-sources",
    tag: "Data Lineage",
    summary: "List data sources for use case",
    parameters: [idPathParam("usecaseId")],
  },

  {
    procedure: "integrations.listWebhooks",
    method: "get",
    path: "/trpc/webhooks",
    tag: "Webhooks",
    summary: "List webhook endpoints",
  },
  {
    procedure: "integrations.webhookById",
    method: "get",
    path: "/trpc/webhooks/{id}",
    tag: "Webhooks",
    summary: "Get webhook endpoint",
    parameters: [idPathParam()],
  },
  {
    procedure: "integrations.createWebhook",
    method: "post",
    path: "/trpc/webhooks",
    tag: "Webhooks",
    summary: "Create webhook endpoint",
    requestBody: true,
  },
  {
    procedure: "integrations.updateWebhook",
    method: "patch",
    path: "/trpc/webhooks/{id}",
    tag: "Webhooks",
    summary: "Update webhook endpoint",
    requestBody: true,
    parameters: [idPathParam()],
  },
  {
    procedure: "integrations.deleteWebhook",
    method: "delete",
    path: "/trpc/webhooks/{id}",
    tag: "Webhooks",
    summary: "Delete webhook endpoint",
    parameters: [idPathParam()],
  },
  {
    procedure: "integrations.regenerateSecret",
    method: "post",
    path: "/trpc/webhooks/{id}/regenerate-secret",
    tag: "Webhooks",
    summary: "Regenerate webhook secret",
    parameters: [idPathParam()],
  },

  {
    procedure: "redteam.library.builtin",
    method: "get",
    path: "/trpc/redteam/library/builtin",
    tag: "Red Team",
    summary: "List built-in red-team prompts",
  },
  {
    procedure: "redteam.library.builtinDetail",
    method: "get",
    path: "/trpc/redteam/library/builtin/{slug}",
    tag: "Red Team",
    summary: "Get built-in red-team prompt",
    parameters: [idPathParam("slug")],
  },
  {
    procedure: "redteam.library.customList",
    method: "get",
    path: "/trpc/redteam/library/custom",
    tag: "Red Team",
    summary: "List custom red-team prompts",
  },
  {
    procedure: "redteam.library.customUpload",
    method: "post",
    path: "/trpc/redteam/library/custom",
    tag: "Red Team",
    summary: "Upload custom red-team prompts",
    requestBody: true,
  },
  {
    procedure: "redteam.library.customDelete",
    method: "delete",
    path: "/trpc/redteam/library/custom/{setName}",
    tag: "Red Team",
    summary: "Delete custom prompt set",
    parameters: [idPathParam("setName")],
  },
  {
    procedure: "redteam.runs.list",
    method: "get",
    path: "/trpc/redteam/runs",
    tag: "Red Team",
    summary: "List red-team runs",
    parameters: [limitQueryParam],
  },
  {
    procedure: "redteam.runs.get",
    method: "get",
    path: "/trpc/redteam/runs/{id}",
    tag: "Red Team",
    summary: "Get red-team run",
    parameters: [idPathParam()],
  },
  {
    procedure: "redteam.modelCard.generate",
    method: "post",
    path: "/trpc/redteam/model-cards",
    tag: "Red Team",
    summary: "Generate model card",
    requestBody: true,
  },

  {
    procedure: "incident.list",
    method: "get",
    path: "/trpc/incidents",
    tag: "Incidents",
    summary: "List incidents",
    parameters: [limitQueryParam],
  },
  {
    procedure: "incident.byId",
    method: "get",
    path: "/trpc/incidents/{id}",
    tag: "Incidents",
    summary: "Get incident",
    parameters: [idPathParam()],
  },
  {
    procedure: "incident.create",
    method: "post",
    path: "/trpc/incidents",
    tag: "Incidents",
    summary: "Create incident",
    requestBody: true,
  },
  {
    procedure: "incident.updateStatus",
    method: "patch",
    path: "/trpc/incidents/{id}/status",
    tag: "Incidents",
    summary: "Update incident status",
    requestBody: true,
    parameters: [idPathParam()],
  },
  {
    procedure: "incident.openCount",
    method: "get",
    path: "/trpc/incidents/open-count",
    tag: "Incidents",
    summary: "Count open incidents",
  },

  {
    procedure: "providerConnection.list",
    method: "get",
    path: "/trpc/provider-connections",
    tag: "Provider Connections",
    summary: "List provider connections",
  },
  {
    procedure: "providerConnection.get",
    method: "get",
    path: "/trpc/provider-connections/{id}",
    tag: "Provider Connections",
    summary: "Get provider connection",
    parameters: [idPathParam()],
  },
  {
    procedure: "providerConnection.catalog",
    method: "get",
    path: "/trpc/provider-connections/catalog",
    tag: "Provider Connections",
    summary: "Get provider catalog",
  },
  {
    procedure: "providerConnection.create",
    method: "post",
    path: "/trpc/provider-connections",
    tag: "Provider Connections",
    summary: "Create provider connection",
    requestBody: true,
  },
  {
    procedure: "providerConnection.update",
    method: "patch",
    path: "/trpc/provider-connections/{id}",
    tag: "Provider Connections",
    summary: "Update provider connection",
    requestBody: true,
    parameters: [idPathParam()],
  },
  {
    procedure: "providerConnection.delete",
    method: "delete",
    path: "/trpc/provider-connections/{id}",
    tag: "Provider Connections",
    summary: "Delete provider connection",
    parameters: [idPathParam()],
  },
  {
    procedure: "providerConnection.ping",
    method: "post",
    path: "/trpc/provider-connections/{id}/ping",
    tag: "Provider Connections",
    summary: "Ping provider connection",
    parameters: [idPathParam()],
  },

  {
    procedure: "reports.templates",
    method: "get",
    path: "/trpc/reports/templates",
    tag: "Reports",
    summary: "List report templates",
  },
  {
    procedure: "reports.list",
    method: "get",
    path: "/trpc/reports",
    tag: "Reports",
    summary: "List generated reports",
    parameters: [limitQueryParam],
  },
  {
    procedure: "reports.get",
    method: "get",
    path: "/trpc/reports/{id}",
    tag: "Reports",
    summary: "Get generated report",
    parameters: [idPathParam()],
  },
  {
    procedure: "reports.generate",
    method: "post",
    path: "/trpc/reports",
    tag: "Reports",
    summary: "Generate report",
    requestBody: true,
  },
  {
    procedure: "reports.delete",
    method: "delete",
    path: "/trpc/reports/{id}",
    tag: "Reports",
    summary: "Delete generated report",
    parameters: [idPathParam()],
  },

  {
    procedure: "finops.cost.summary",
    method: "get",
    path: "/trpc/finops/cost/summary",
    tag: "FinOps",
    summary: "Get cost summary",
  },
  {
    procedure: "finops.cost.totals",
    method: "get",
    path: "/trpc/finops/cost/totals",
    tag: "FinOps",
    summary: "Get cost totals",
  },
  {
    procedure: "finops.budget.list",
    method: "get",
    path: "/trpc/finops/budgets",
    tag: "FinOps",
    summary: "List budgets",
  },
  {
    procedure: "finops.budget.create",
    method: "post",
    path: "/trpc/finops/budgets",
    tag: "FinOps",
    summary: "Create budget",
    requestBody: true,
  },
  {
    procedure: "finops.budget.update",
    method: "patch",
    path: "/trpc/finops/budgets/{id}",
    tag: "FinOps",
    summary: "Update budget",
    requestBody: true,
    parameters: [idPathParam()],
  },
  {
    procedure: "finops.budget.delete",
    method: "delete",
    path: "/trpc/finops/budgets/{id}",
    tag: "FinOps",
    summary: "Delete budget",
    parameters: [idPathParam()],
  },
  {
    procedure: "finops.pricing.catalog",
    method: "get",
    path: "/trpc/finops/pricing",
    tag: "FinOps",
    summary: "Get pricing catalog",
  },
  {
    procedure: "finops.pricing.setOverride",
    method: "post",
    path: "/trpc/finops/pricing/overrides",
    tag: "FinOps",
    summary: "Set pricing override",
    requestBody: true,
  },
  {
    procedure: "finops.pricing.clearOverride",
    method: "delete",
    path: "/trpc/finops/pricing/overrides",
    tag: "FinOps",
    summary: "Clear pricing override",
    requestBody: true,
  },

  {
    procedure: "riskCopilot.isEnabled",
    method: "get",
    path: "/trpc/risk-copilot/enabled",
    tag: "Risk Copilot",
    summary: "Check if risk copilot is enabled",
  },
  {
    procedure: "riskCopilot.usageToday",
    method: "get",
    path: "/trpc/risk-copilot/usage-today",
    tag: "Risk Copilot",
    summary: "Get today's usage count and limit",
  },
  {
    procedure: "riskCopilot.suggest",
    method: "post",
    path: "/trpc/risk-copilot/suggest",
    tag: "Risk Copilot",
    summary: "Run AI risk suggestion for a use case",
    requestBody: true,
  },
  {
    procedure: "riskCopilot.latest",
    method: "get",
    path: "/trpc/risk-copilot/latest",
    tag: "Risk Copilot",
    summary: "Get latest suggestion for a use case",
    parameters: [
      {
        name: "usecaseId",
        in: "query",
        required: true,
        schema: { type: "string" },
      },
    ],
  },
  {
    procedure: "riskCopilot.history",
    method: "get",
    path: "/trpc/risk-copilot/history",
    tag: "Risk Copilot",
    summary: "Get suggestion history for a use case",
    parameters: [
      {
        name: "usecaseId",
        in: "query",
        required: true,
        schema: { type: "string" },
      },
      limitQueryParam,
    ],
  },
  {
    procedure: "riskCopilot.decide",
    method: "post",
    path: "/trpc/risk-copilot/decide",
    tag: "Risk Copilot",
    summary: "Accept or reject a suggestion item",
    requestBody: true,
  },
  {
    procedure: "riskCopilot.bulkDecide",
    method: "post",
    path: "/trpc/risk-copilot/bulk-decide",
    tag: "Risk Copilot",
    summary: "Bulk accept or reject suggestion items",
    requestBody: true,
  },
  {
    procedure: "riskCopilot.unlink",
    method: "post",
    path: "/trpc/risk-copilot/unlink",
    tag: "Risk Copilot",
    summary: "Remove a risk link from a use case",
    requestBody: true,
  },
  {
    procedure: "riskCopilot.linkedRisks",
    method: "get",
    path: "/trpc/risk-copilot/linked-risks",
    tag: "Risk Copilot",
    summary: "List risks linked to a use case",
    parameters: [
      {
        name: "usecaseId",
        in: "query",
        required: true,
        schema: { type: "string" },
      },
    ],
  },

  {
    procedure: "incidentRca.isEnabled",
    method: "get",
    path: "/trpc/incident-rca/enabled",
    tag: "Incident RCA",
    summary: "Check if incident RCA is enabled",
  },
  {
    procedure: "incidentRca.suggest",
    method: "post",
    path: "/trpc/incident-rca/suggest",
    tag: "Incident RCA",
    summary: "Run AI root-cause analysis for an incident",
    requestBody: true,
  },
  {
    procedure: "incidentRca.latest",
    method: "get",
    path: "/trpc/incident-rca/latest",
    tag: "Incident RCA",
    summary: "Get latest RCA draft for an incident",
    parameters: [
      {
        name: "incidentId",
        in: "query",
        required: true,
        schema: { type: "string" },
      },
    ],
  },
  {
    procedure: "incidentRca.history",
    method: "get",
    path: "/trpc/incident-rca/history",
    tag: "Incident RCA",
    summary: "Get RCA draft history for an incident",
    parameters: [
      {
        name: "incidentId",
        in: "query",
        required: true,
        schema: { type: "string" },
      },
      limitQueryParam,
    ],
  },
  {
    procedure: "incidentRca.accept",
    method: "post",
    path: "/trpc/incident-rca/accept",
    tag: "Incident RCA",
    summary: "Accept RCA draft and write to incident root cause",
    requestBody: true,
  },
  {
    procedure: "incidentRca.reject",
    method: "post",
    path: "/trpc/incident-rca/reject",
    tag: "Incident RCA",
    summary: "Reject RCA draft",
    requestBody: true,
  },
];

export function getTrpcOpenApiPaths(): Record<string, OpenApiPathItem> {
  const paths: Record<string, OpenApiPathItem> = {};
  for (const endpoint of endpoints) {
    paths[endpoint.path] ??= {};
    paths[endpoint.path][endpoint.method] = {
      tags: [endpoint.tag],
      summary: endpoint.summary,
      description: `Documentation proxy for tRPC procedure \`${endpoint.procedure}\`. The canonical runtime endpoint remains \`/api/trpc/${endpoint.procedure}\` using the tRPC HTTP protocol.`,
      operationId: endpoint.procedure.replaceAll(".", "_"),
      security: [{ cookieAuth: [] }],
      parameters: endpoint.parameters,
      ...(endpoint.requestBody ? { requestBody: jsonBody } : {}),
      responses: {
        "200": genericResponse,
        ...errorResponses,
      },
      "x-trpc-procedure": endpoint.procedure,
    };
  }
  return paths;
}

export const trpcOpenApiTags = Array.from(
  new Set(endpoints.map((endpoint) => endpoint.tag)),
).map((name) => ({ name }));
