#!/usr/bin/env node
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const corePath = join(here, "core.prisma");
const modulesDir = join(here, "modules");
const outPath = join(here, "schema.prisma");

const core = readFileSync(corePath, "utf8");

const moduleFiles = readdirSync(modulesDir)
  .filter((f) => f.endsWith(".prisma"))
  .sort();

const fragments = moduleFiles.map((f) => {
  const body = readFileSync(join(modulesDir, f), "utf8");
  const stripped = body
    .replace(/^generator[\s\S]*?\}\s*/gm, "")
    .replace(/^datasource[\s\S]*?\}\s*/gm, "");
  return stripped;
});

// Hoist all enums before models to work around Prisma 6.x WASM parser bug
// where enums in later fragments fail validation when they follow model blocks.
const allEnumBlocks = [];
const modelBlocks = [];

for (const frag of fragments) {
  const enumRe = /^enum\s+\w+\s*\{[^}]+\}/gm;
  let match;
  let lastIndex = 0;
  let foundEnum = false;

  while ((match = enumRe.exec(frag)) !== null) {
    allEnumBlocks.push(match[0]);
    foundEnum = true;
  }

  if (foundEnum) {
    // Remove all enum blocks from fragment
    const withoutEnums = frag.replace(enumRe, "");
    // Also remove leading/trailing blank lines left behind
    const cleaned = withoutEnums.replace(/^\n+/, "").replace(/\n+$/, "");
    if (cleaned.trim()) modelBlocks.push(cleaned);
  } else {
    modelBlocks.push(frag.replace(/^\n+/, "").replace(/\n+$/, ""));
  }
}

const banner = `// AUTO-GENERATED by prisma/build-schema.mjs — DO NOT EDIT.\n// Edit prisma/core.prisma or prisma/modules/*.prisma and re-run.\n\n`;

writeFileSync(
  outPath,
  banner +
    core +
    "\n\n" +
    allEnumBlocks.join("\n\n") +
    "\n\n" +
    modelBlocks.join("\n") +
    "\n",
);
console.log(
  `schema.prisma written (${moduleFiles.length} module fragment(s), ${allEnumBlocks.length} enums hoisted)`,
);
