export const ROLES = [
  "admin",
  "risk_officer",
  "ai_owner",
  "auditor",
  "viewer",
] as const;
export type Role = (typeof ROLES)[number];

export const RESOURCES = [
  "inventory",
  "risk",
  "policy",
  "data_lineage",
  "evidence",
  "workflow",
  "audit",
  "integrations",
  "provider",
  "org",
  "maturity",
  "incident",
  "reports",
  "finops",
  "redteam",
  "fria",
  "aivtf",
  "mindforge-checklist",
  "asi-redteam-checklist",
  "agentic-governance",
  "frontier-risk-tier",
  "transparency-report",
  "incident-trends",
  "mcp",
  "drift",
  "materiality",
  "fairness",
  "vendor",
  "go-live",
  "external-reports",
  "alignment-audit",
  "usage-insights",
  "trust-center",
] as const;
export type Resource = (typeof RESOURCES)[number];

export type Action = "read" | "write" | "delete" | "approve";
export type Permission = `${Resource}.${Action}`;

const ALL: Action[] = ["read", "write", "delete"];

function expand(per: Partial<Record<Resource, Action[]>>): Set<Permission> {
  const s = new Set<Permission>();
  for (const [res, actions] of Object.entries(per) as [Resource, Action[]][]) {
    for (const a of actions) s.add(`${res}.${a}` as Permission);
  }
  return s;
}

export const MATRIX: Record<Role, Set<Permission>> = {
  admin: expand({
    ...Object.fromEntries(RESOURCES.map((r) => [r, ALL])),
    fria: [...ALL, "approve"],
    aivtf: [...ALL, "approve"],
    "mindforge-checklist": [...ALL, "approve"],
    "asi-redteam-checklist": [...ALL, "approve"],
    "agentic-governance": [...ALL, "approve"],
    "frontier-risk-tier": [...ALL, "approve"],
    "transparency-report": [...ALL, "approve"],
    "trust-center": [...ALL, "approve"],
    "go-live": [...ALL, "approve"],
  } as Record<Resource, Action[]>),

  risk_officer: expand({
    inventory: ["read"],
    risk: ALL,
    policy: ALL,
    data_lineage: ["read"],
    evidence: ["read", "write"],
    workflow: ["read", "write"],
    audit: ["read"],
    integrations: ["read"],
    provider: ["read"],
    maturity: ["read", "write"],
    org: ["read"],
    incident: ALL,
    reports: ALL,
    finops: ["read", "write"],
    redteam: ["read", "write"],
    fria: ["read", "write", "approve"],
    aivtf: ["read", "write", "approve"],
    "mindforge-checklist": ["read", "write", "approve"],
    "asi-redteam-checklist": ["read", "write", "approve"],
    "agentic-governance": ["read", "write", "approve"],
    "frontier-risk-tier": ["read", "write", "approve"],
    "transparency-report": ["read", "write", "approve"],
    "trust-center": ["read", "write", "approve"],
    "incident-trends": ["read", "write"],
    "usage-insights": ["read", "write"],
    mcp: ["read", "write"],
    drift: ["read", "write"],
    materiality: ["read", "write"],
    fairness: ["read", "write"],
    vendor: ["read", "write"],
    "go-live": ["read", "write", "approve"],
    "external-reports": ["read", "write"],
    "alignment-audit": ["read", "write", "delete"],
  }),

  ai_owner: expand({
    inventory: ALL,
    risk: ["read"],
    policy: ALL,
    data_lineage: ["read", "write"],
    evidence: ["read", "write"],
    workflow: ["read", "write"],
    audit: ["read"],
    integrations: ["read", "write"],
    provider: ["read"],
    maturity: ["read"],
    org: ["read"],
    incident: ["read", "write"],
    reports: ["read"],
    finops: ["read"],
    redteam: ["read", "write"],
    fria: ["read", "write"],
    aivtf: ["read", "write"],
    "mindforge-checklist": ["read", "write"],
    "asi-redteam-checklist": ["read", "write"],
    "agentic-governance": ["read", "write"],
    "frontier-risk-tier": ["read", "write"],
    "transparency-report": ["read", "write"],
    "trust-center": ["read", "write"],
    "incident-trends": ["read", "write"],
    "usage-insights": ["read", "write"],
    mcp: ["read"],
    drift: ["read", "write"],
    materiality: ["read", "write"],
    fairness: ["read", "write"],
    vendor: ["read", "write"],
    "go-live": ["read", "write", "approve"],
    "external-reports": ["read", "write"],
    "alignment-audit": ["read", "write"],
  }),

  auditor: expand({
    inventory: ["read"],
    risk: ["read"],
    policy: ["read"],
    data_lineage: ["read"],
    evidence: ["read"],
    workflow: ["read"],
    audit: ["read"],
    integrations: ["read"],
    provider: ["read"],
    maturity: ["read"],
    org: ["read"],
    incident: ["read"],
    reports: ["read", "write"],
    finops: ["read"],
    redteam: ["read"],
    fria: ["read"],
    aivtf: ["read"],
    "mindforge-checklist": ["read"],
    "asi-redteam-checklist": ["read"],
    "agentic-governance": ["read"],
    "frontier-risk-tier": ["read"],
    "transparency-report": ["read"],
    "trust-center": ["read"],
    "incident-trends": ["read"],
    "usage-insights": ["read"],
    mcp: ["read"],
    drift: ["read"],
    materiality: ["read"],
    fairness: ["read"],
    vendor: ["read"],
    "go-live": ["read"],
    "external-reports": ["read"],
    "alignment-audit": ["read"],
  }),

  viewer: expand({
    inventory: ["read"],
    risk: ["read"],
    policy: ["read"],
    data_lineage: ["read"],
    evidence: ["read"],
    workflow: ["read"],
    audit: ["read"],
    integrations: ["read"],
    provider: ["read"],
    maturity: ["read"],
    org: ["read"],
    incident: ["read"],
    reports: ["read"],
    finops: ["read"],
    redteam: ["read"],
    fria: ["read"],
    aivtf: ["read"],
    "mindforge-checklist": ["read"],
    "asi-redteam-checklist": ["read"],
    "agentic-governance": ["read"],
    "frontier-risk-tier": ["read"],
    "transparency-report": ["read"],
    "trust-center": ["read"],
    "incident-trends": ["read"],
    "usage-insights": ["read"],
    mcp: ["read"],
    drift: ["read"],
    materiality: ["read"],
    fairness: ["read"],
    vendor: ["read"],
    "go-live": ["read"],
    "external-reports": ["read"],
    "alignment-audit": ["read"],
  }),
};
