import type { ModelCardData } from "./aggregator";

export function renderMarkdown(d: ModelCardData): string {
  const lines: string[] = [];

  lines.push(`# Model Card: ${d.usecase.name}`);
  lines.push("");
  lines.push(
    `> Generated ${d.generatedAt.toISOString().slice(0, 10)} by ${d.generatedBy.name}`,
  );
  lines.push("");

  lines.push("## 1. Overview");
  lines.push(`- **Use case**: ${d.usecase.name}`);
  lines.push(`- **Lifecycle stage**: \`${d.usecase.lifecycleStage}\``);
  lines.push(`- **Autonomy level**: \`${d.usecase.autonomyLevel}\``);
  lines.push(`- **Deployment type**: \`${d.usecase.deploymentType}\``);
  lines.push("");

  lines.push("## 2. Intended Use");
  lines.push(d.usecase.description || "_(not documented)_");
  lines.push("");

  lines.push("## 3. Owners");
  if (d.inventory.ownerName || d.inventory.ownerEmail) {
    lines.push(
      `- **Technical owner**: ${d.inventory.ownerName ?? "(unnamed)"}${d.inventory.ownerEmail ? ` <${d.inventory.ownerEmail}>` : ""}`,
    );
  } else {
    lines.push("- **Technical owner**: (unassigned)");
  }
  lines.push("");

  lines.push("## 4. Risk Assessment Summary");
  if (d.risk.topRisks.length === 0) {
    lines.push("_(no risk assessments recorded)_");
  } else {
    for (const r of d.risk.topRisks) {
      lines.push(
        `- **${r.severity.toUpperCase()}** — ${r.title} _(${r.assessedAt.toISOString().slice(0, 10)})_`,
      );
    }
  }
  lines.push("");

  lines.push("## 5. Red-team Evaluation Results");
  if (d.evaluations.length === 0) {
    lines.push("_(no evaluations run)_");
  } else {
    for (const e of d.evaluations) {
      const passRate =
        e.totalPrompts > 0
          ? ((e.passedCount / e.totalPrompts) * 100).toFixed(1)
          : "—";
      lines.push(
        `- ${e.createdAt.toISOString().slice(0, 10)} · \`${e.model}\` · ${e.passedCount} / ${e.totalPrompts} passed (${passRate}%) · failures: ${e.failedCount}, errors: ${e.errorCount}`,
      );
    }
  }
  lines.push("");

  lines.push("## 6. Known Limitations & Caveats");
  lines.push(d.knownLimitations);
  lines.push("");

  lines.push("## 7. References");
  lines.push(`- Inventory: \`/dashboard/inventory/${d.usecase.id}\``);
  lines.push("- Generated by AIGP-Lite Model Card v1.0");

  return lines.join("\n");
}
