import React from "react";
import { Document, Page, Text, StyleSheet, pdf } from "@react-pdf/renderer";
import type { ModelCardData } from "./aggregator";

const s = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: "Helvetica" },
  h1: { fontSize: 18, fontWeight: 700, marginBottom: 8 },
  h2: {
    fontSize: 12,
    fontWeight: 700,
    marginTop: 12,
    marginBottom: 4,
    borderBottom: 1,
    paddingBottom: 2,
  },
  para: { marginBottom: 4 },
  meta: { color: "#666", marginBottom: 6, fontSize: 9 },
  sev: { fontWeight: 700 },
  sevHigh: { color: "#a00" },
  sevMed: { color: "#b27300" },
  sevLow: { color: "#666" },
});

function sevStyle(severity: string) {
  if (severity === "critical" || severity === "high") return s.sevHigh;
  if (severity === "medium") return s.sevMed;
  return s.sevLow;
}

function Doc({ data }: { data: ModelCardData }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <Text style={s.h1}>Model Card: {data.usecase.name}</Text>
        <Text style={s.meta}>
          Generated {data.generatedAt.toISOString().slice(0, 10)} by{" "}
          {data.generatedBy.name}
        </Text>

        <Text style={s.h2}>1. Overview</Text>
        <Text style={s.para}>Use case: {data.usecase.name}</Text>
        <Text style={s.para}>
          Lifecycle stage: {data.usecase.lifecycleStage}
        </Text>
        <Text style={s.para}>Autonomy level: {data.usecase.autonomyLevel}</Text>
        <Text style={s.para}>
          Deployment type: {data.usecase.deploymentType}
        </Text>

        <Text style={s.h2}>2. Intended Use</Text>
        <Text style={s.para}>
          {data.usecase.description || "(not documented)"}
        </Text>

        <Text style={s.h2}>3. Owners</Text>
        <Text style={s.para}>
          Technical owner: {data.inventory.ownerName ?? "(unassigned)"}
          {data.inventory.ownerEmail ? ` <${data.inventory.ownerEmail}>` : ""}
        </Text>

        <Text style={s.h2}>4. Risk Assessment Summary</Text>
        {data.risk.topRisks.length === 0 ? (
          <Text style={s.para}>(no risk assessments recorded)</Text>
        ) : (
          data.risk.topRisks.map((r) => (
            <Text key={r.id} style={s.para}>
              <Text style={[s.sev, sevStyle(r.severity)]}>
                [{r.severity.toUpperCase()}]
              </Text>{" "}
              {r.title}
              {"  "}({r.assessedAt.toISOString().slice(0, 10)})
            </Text>
          ))
        )}

        <Text style={s.h2}>5. Red-team Evaluation Results</Text>
        {data.evaluations.length === 0 ? (
          <Text style={s.para}>(no evaluations run)</Text>
        ) : (
          data.evaluations.map((e) => {
            const passRate =
              e.totalPrompts > 0
                ? ((e.passedCount / e.totalPrompts) * 100).toFixed(1)
                : "—";
            return (
              <Text key={e.id} style={s.para}>
                {e.createdAt.toISOString().slice(0, 10)} · {e.model} ·{" "}
                {e.passedCount}/{e.totalPrompts} passed ({passRate}%) ·
                failures: {e.failedCount}, errors: {e.errorCount}
              </Text>
            );
          })
        )}

        <Text style={s.h2}>6. Known Limitations</Text>
        <Text style={s.para}>{data.knownLimitations}</Text>

        <Text style={s.h2}>7. References</Text>
        <Text style={s.para}>
          Inventory: /dashboard/inventory/{data.usecase.id}
        </Text>
        <Text style={s.para}>Generated by AIGP-Lite Model Card v1.0</Text>
      </Page>
    </Document>
  );
}

export async function renderModelCardPdf(data: ModelCardData): Promise<Buffer> {
  const blob = await pdf(<Doc data={data} />).toBlob();
  return Buffer.from(await blob.arrayBuffer());
}
