export {
  LayoutDashboard,
  Boxes,
  ShieldAlert,
  ScrollText,
  Gauge,
  GitBranch,
  Paperclip,
  FileText,
  Network,
  Plug,
  Cpu,
  Webhook,
  FileBarChart2,
  Wallet,
  ShieldCheck,
  AlertTriangle,
  Building2,
  BookOpen,
  Search,
  Bell,
  Server,
  Activity,
  ClipboardCheck,
  ListChecks,
  User,
  Users,
  Settings,
  MoreHorizontal,
  CheckCircle2,
  AlertCircle,
  XCircle,
  Clock,
  AlertOctagon,
  Loader2,
  Inbox,
  Plus,
  Pencil,
  Trash2,
  Download,
  Upload,
  ExternalLink,
  Globe,
  Copy,
  Filter,
  ArrowUpDown,
  RefreshCw,
  ShieldQuestion,
  Eye,
  EyeOff,
  Lock,
  GripVertical,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
} from "lucide-react";

import {
  LayoutDashboard,
  Boxes,
  ShieldAlert,
  ScrollText,
  Gauge,
  Newspaper,
  GitBranch,
  Paperclip,
  FileText,
  Network,
  Plug,
  Cpu,
  Webhook,
  FileBarChart2,
  Wallet,
  ShieldCheck,
  AlertTriangle,
  Server,
  Activity,
  Users,
  ClipboardCheck,
  ListChecks,
  Building2,
  Megaphone,
  Globe,
  ShieldQuestion,
  BarChart3,
} from "lucide-react";

export const MODULE_ICONS = {
  overview: LayoutDashboard,
  inventory: Boxes,
  risk: ShieldAlert,
  policy: ScrollText,
  maturity: Gauge,
  workflow: GitBranch,
  evidence: Paperclip,
  audit: FileText,
  "data-lineage": Network,
  integrations: Plug,
  providers: Cpu,
  connectors: Webhook,
  reports: FileBarChart2,
  finops: Wallet,
  redteam: ShieldCheck,
  incidents: AlertTriangle,
  mcp: Server,
  drift: Activity,
  aivtf: ClipboardCheck,
  "mindforge-checklist": ListChecks,
  "asi-redteam-checklist": ShieldCheck,
  "agentic-governance": ShieldCheck,
  "frontier-risk-tier": Gauge,
  "transparency-report": Newspaper,
  "incident-trends": Activity,
  vendors: Building2,
  members: Users,
  "external-reports": Megaphone,
  "alignment-audit": ShieldQuestion,
  "usage-insights": BarChart3,
  "trust-center": Globe,
} as const;

export type ModuleSlug = keyof typeof MODULE_ICONS;
